ALTER TABLE `user_member`
ADD COLUMN `phone` VARCHAR(20) NOT NULL AFTER `email`,
ADD COLUMN `role` VARCHAR(20) NOT NULL AFTER `phone`,
ADD COLUMN `sex` VARCHAR(10) NOT NULL AFTER `role`,
ADD COLUMN `id_number` VARCHAR(20) NOT NULL AFTER `sex`; 